services:
  server:
    build: ./flask
    hostname: server       # 컨테이너 내부에서 식별될 호스트 이름
    container_name: server
    volumes:
      - ./server_vol:/app/captures # 로컬의 ./server 폴더와 마운트
    ports:
      - "8000:8000"      # 호스트에서도 30000번 포트 확인 가능하도록 매핑
    command: ["gunicorn", "--workers", "1", "-k", "gevent", "--bind", "0.0.0.0:8000", "--timeout", "10", "--keep-alive", "10", "app:app", "--log-level", "debug"]

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client_vol:/app/captures # 로컬의 ./client 폴더와 마운트
    command: ["sleep", "infinity"]