services:
  server:
    build: ./flask
    hostname: server       # 컨테이너 내부에서 식별될 호스트 이름
    container_name: server
    volumes:
      - ./server:/app/captures # 로컬의 ./server 폴더와 마운트
    ports:
      - "8000:8000"      # 호스트에서도 30000번 포트 확인 가능하도록 매핑
    command: ["gunicorn", "--workers", "4", "-k", "gevent", "--bind", "0.0.0.0:8000", "--timeout", "${TIMEOUT}", "--keep-alive", "${KEEP_ALIVE}", "app:app"]

  client:
    build: .
    container_name: client
    volumes:
      - ./client:/app/captures # 로컬의 ./client 폴더와 마운트
    command: ["sleep", "infinity"]