helmDefaults:
  kubeContext: kind-1-33
  createNamespace: true

missingFileHandler: Error

releases:
  - name: base
    namespace: istio-system
    chart: ./charts/base
    values:
      - ./values/istio-base.yaml

  - name: gateway
    namespace: istio-system
    chart: ./charts/gateway
    values:
      - ./values/istio-gateway.yaml

  - name: istiod
    namespace: istio-system
    chart: ./charts/istiod
    values:
      - ./values/istio-istiod.yaml